# NÄRA LÖST (många edge cases kvar)

class Polygon:
    def __init__(self, numVertices, vertices = []): # [(x, y)]
        self.vertices = []
        if len(vertices) == 0:
            for _ in range(numVertices):
                self.vertices.append([float(s) for s in input().split()]) # [x, y]
        else:
            self.vertices = vertices
    
    def getVertices(self): # [(x, y)]
        return self.vertices
    
    def getEdges(self): # generator -> ((x, y), (z, w))
        numVertices = len(self.vertices)
        for i in range(numVertices):
            a, b = self.vertices[i], self.vertices[(i+1) % numVertices]
            yield a, b
    
    def getSubTriangles(self): # suboptimal - many permutations
        for a in self.vertices:
            for b in self.vertices:
                for c in self.vertices:
                    if (a != b) and (b != c) and (c != a):
                        yield Polygon(0, [a, b, c])

    @staticmethod
    def convexHull(points):
        points = sorted(set(tuple(p) for p in points))

        def cross(o, a, b):
            return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

        lower = []
        for p in points:
            while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 1e-10:
                lower.pop()
            lower.append(p)

        upper = []
        for p in reversed(points):
            while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 1e-10:
                upper.pop()
            upper.append(p)

        return lower[:-1] + upper[:-1]

    @staticmethod
    def strictlyInsideConvex(vertices, point):
        if len(vertices) < 3:
            return False

        sign = 0
        x, y = point
        numVertices = len(vertices)
        for i in range(numVertices):
            x1, y1 = vertices[i]
            x2, y2 = vertices[(i + 1) % numVertices]
            cross = (x2 - x1) * (y - y1) - (y2 - y1) * (x - x1)

            if abs(cross) <= 1e-10:
                return False

            if sign == 0:
                sign = 1 if cross > 0 else -1
            elif (cross > 0) != (sign > 0):
                return False

        return True
    
    # FUNCTION GENERATED BY AI
    def centerOfMass(self):
        area2 = 0.0
        cx = 0.0
        cy = 0.0

        numVertices = len(self.vertices)

        for i in range(numVertices):
            x1, y1 = self.vertices[i]
            x2, y2 = self.vertices[(i + 1) % numVertices]

            cross = x1 * y2 - x2 * y1
            area2 += cross
            cx += (x1 + x2) * cross
            cy += (y1 + y2) * cross

        cx /= 3 * area2
        cy /= 3 * area2

        return [cx, cy]
    
    def contains(self, point): # check if a point is inside the polygon - ray casts
        a, b = point, [10**9, point[1]] # extends to the right
        numIntersects = len(self.findIntersections(a, b))
        return True if (numIntersects % 2) == 1 else False
    
    def findIntersections(self, a, b):
        intersections = []
        for c, d in self.getEdges():
            hit = self.segment_segment_intersection(a, b, c, d)
            if hit is not None:
                intersections.append(hit)
        return intersections
    
    # FUNCTION GENERATED BY AI
    @staticmethod
    def segment_segment_intersection(a, b, c, d):
        x1, y1 = a
        x2, y2 = b
        x3, y3 = c
        x4, y4 = d

        den = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4)

        if abs(den) < 1e-10:
            return None

        px = ((x1 * y2 - y1 * x2) * (x3 - x4) - (x1 - x2) * (x3 * y4 - y3 * x4)) / den
        py = ((x1 * y2 - y1 * x2) * (y3 - y4) - (y1 - y2) * (x3 * y4 - y3 * x4)) / den

        if (
            min(x1, x2) - 1e-10 <= px <= max(x1, x2) + 1e-10 and
            min(y1, y2) - 1e-10 <= py <= max(y1, y2) + 1e-10 and
            min(x3, x4) - 1e-10 <= px <= max(x3, x4) + 1e-10 and
            min(y3, y4) - 1e-10 <= py <= max(y3, y4) + 1e-10
        ):
            return (px, py)

        return None

def intput():
    return int(input())

def checkIfSupported(glass: Polygon, supportPolygons): # -> None, "stable", "unstable"
    supports = [] # (x, y)
    for otherPolygon in supportPolygons:
        
        # supports inside glass
        for p in otherPolygon.getVertices():
            if glass.contains(p):
                supports.append(p)
        
        # glass inside supports
        for p in glass.getVertices():
            if otherPolygon.contains(p):
                supports.append(p)

        # edge intersections
        for a, b in otherPolygon.getEdges(): # lines from a to b
            intersections = glass.findIntersections(a, b)
            supports += intersections

    # determine if the glass will tilt or not

    if len(supports) == 0:
        return None

    if len(supports) >= 3: # check if the glass' center of mass is held up by OTHERS
        glassCenter = glass.centerOfMass()
        if Polygon.strictlyInsideConvex(Polygon.convexHull(supports), glassCenter):
            return "stable"
        
    return "unstable" # center not inside any support triangle -> will tilt

glass = Polygon(intput())
base = Polygon(intput())
others = [Polygon(intput()) for _ in range(intput())]

# check support by others
othersResult = checkIfSupported(glass, others)
if othersResult is not None:
    print(othersResult)
    exit()

# check support by base
baseResult = checkIfSupported(glass, [base])
print(baseResult if (baseResult is not None) else "unstable")
